# Generated by Django 4.2.7 on 2024-02-08 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LongStoryApp', '0002_remove_story_story_story_story_shown'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name_plural': 'story'},
        ),
    ]
